export const GRIEVANCE_CREATE_REQUEST = "GRIEVANCE_CREATE_REQUEST";
export const GRIEVANCE_CREATE_SUCCESS = "GRIEVANCE_CREATE_SUCCESS";
export const GRIEVANCE_CREATE_FAIL = "GRIEVANCE_CREATE_FAIL";
export const GRIEVANCE_CREATE_RESET = "GRIEVANCE_CREATE_RESET";

export const GRIEVANCE_MY_LIST_REQUEST = "GRIEVANCE_MY_LIST_REQUEST";
export const GRIEVANCE_MY_LIST_SUCCESS = "GRIEVANCE_MY_LIST_SUCCESS";
export const GRIEVANCE_MY_LIST_FAIL = "GRIEVANCE_MY_LIST_FAIL";

export const GRIEVANCE_ALL_LIST_REQUEST = "GRIEVANCE_ALL_LIST_REQUEST";
export const GRIEVANCE_ALL_LIST_SUCCESS = "GRIEVANCE_ALL_LIST_SUCCESS";
export const GRIEVANCE_ALL_LIST_FAIL = "GRIEVANCE_ALL_LIST_FAIL";

export const GRIEVANCE_UPDATE_REQUEST = "GRIEVANCE_UPDATE_REQUEST";
export const GRIEVANCE_UPDATE_SUCCESS = "GRIEVANCE_UPDATE_SUCCESS";
export const GRIEVANCE_UPDATE_FAIL = "GRIEVANCE_UPDATE_FAIL";
export const GRIEVANCE_UPDATE_RESET = "GRIEVANCE_UPDATE_RESET";
