export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST'
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS'
export const NOTIFICATION_LIST_FAIL = 'NOTIFICATION_LIST_FAIL'

export const NOTIFICATION_CREATE_REQUEST = 'NOTIFICATION_CREATE_REQUEST'
export const NOTIFICATION_CREATE_SUCCESS = 'NOTIFICATION_CREATE_SUCCESS'
export const NOTIFICATION_CREATE_FAIL = 'NOTIFICATION_CREATE_FAIL'
export const NOTIFICATION_CREATE_RESET = 'NOTIFICATION_CREATE_RESET'

export const NOTIFICATION_MARK_READ_REQUEST = 'NOTIFICATION_MARK_READ_REQUEST'
export const NOTIFICATION_MARK_READ_SUCCESS = 'NOTIFICATION_MARK_READ_SUCCESS'
export const NOTIFICATION_MARK_READ_FAIL = 'NOTIFICATION_MARK_READ_FAIL'
